### PR TITLE
Save score units on the test level and represent it on the changes

### PR DESCRIPTION
**Pull request by dupliaka**
Feature request on unit labeling 
Looks like:
image

Need to update container to include util to the db

### CODE REVIEW

**Comment by rvansa** [comment]
This should definitely not be a property of the Test; you could have it as a property of the Variable, though.

Visually I would put it vertical and vertically centered rather than angled in top left.

**Comment by dupliaka** [comment]
1. In case you have different units you just do not define it in the test and define it as a part of the variable name. I dont see any profit in adding it to variables since you can then make it a  part of the name. 
2. If I put it vertically then it overlaps with the titles of the scale. I tried to put it on the top without any angling but it either overlaps the scale number or it go behind the canvas.

**Comment by dupliaka** [comment]
Maybe then put the label on the mid as at reports

**Comment by rvansa** [comment]
1. So you want to add a "default unit" for all variable names, rather than repeating it for every variable? Hmm, okay, but the it should be still defined in the "Change Detection" tab, and probably hosted in another table. Putting it straight to Test seems very ad-hoc, it's quite unclear what should it relate to. Should that be automatically added as unit to every View component, to Reports etc.?
2. I guess in that case you need to add some offset left from the scale.

**Comment by rvansa** [comment]
1. Yes, if you really find it useful you can put it there. My preference would be having the unit individually for each variable, but I won't object to that.
2. IDK TBH - Recharts are try-and-see for me. I think that `insideLeft` is the right one, but somehow you have to make space in the parent. Maybe put the Label right into the YAxis like here: https://recharts.org/en-US/api/Label

**Comment by dupliaka** [comment]
Ok, lets do one of this: resolve conflicts and merge it as it is or just close

**Comment by rvansa** [comment]
I strongly disagree with adding `unit` to `Test`, therefore closing.

**Pull request closed without merging**
