### PR TITLE
Migration to React 18

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@jesperpedersen @johnaohara 

during the migration Build got success but test are failing
```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ horreum-integration-tests ---
[INFO] Installing C:\Users\shivam sharma\Desktop\My Project\open-source\Horreum\horreum-integration-tests\target\horreum-integration-tests-0.8-SNAPSHOT.jar to C:\Users\shivam sharma\.m2\repository\io\hyperfoil\tools\horreum-integration-tests\0.8-SNAPSHOT\horreum-integration-tests-0.8-SNAPSHOT.jar
[INFO] Installing C:\Users\shivam sharma\Desktop\My Project\open-source\Horreum\horreum-integration-tests\pom.xml to C:\Users\shivam sharma\.m2\repository\io\hyperfoil\tools\horreum-integration-tests\0.8-SNAPSHOT\horreum-integration-tests-0.8-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Horreum 0.8-SNAPSHOT:
[INFO]
[INFO] Horreum ............................................ SUCCESS [  0.922 s]
[INFO] Horreum infra - common ............................. SUCCESS [  3.505 s]
[INFO] Horreum Dev Services - Parent ...................... SUCCESS [  0.039 s]
[INFO] Horreum Dev Services - Runtime ..................... SUCCESS [  2.597 s]
[INFO] Horreum Dev Services - Deployment .................. SUCCESS [  5.204 s]
[INFO] horreum-api ........................................ SUCCESS [ 11.316 s]
[INFO] Horreum Backend .................................... SUCCESS [01:38 min]
[INFO] Horreum Client ..................................... SUCCESS [  1.452 s]
[INFO] Horreum Integration Tests .......................... SUCCESS [ 25.640 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:31 min
[INFO] Finished at: 2023-09-22T12:51:23+05:30
[INFO] ------------------------------------------------------------------------
PS C:\Users\shivam sharma\Desktop\My Project\open-source\Horreum> mvn -Dquarkus.test.continuous-testing=disabled quarkus:dev  -pl '!horreum-integration-tests'
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.hyperfoil.tools:horreum-infra-common:jar:0.8-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.testcontainers:postgresql:jar -> duplicate declaration of version (?) @ line 28, column 21
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.hyperfoil.tools:horreum-backend:jar:0.8-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for io.quarkus:quarkus-maven-plugin is missing. @ line 192, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Horreum                                                            [pom]
[INFO] Horreum infra - common                                             [jar]
[INFO] Horreum Dev Services - Parent                                      [pom]
[INFO] Horreum Dev Services - Runtime                                     [jar]
[INFO] Horreum Dev Services - Deployment                                  [jar]
[INFO] horreum-api                                                        [jar]
[INFO] Horreum Backend                                                    [jar]
[INFO] Horreum Client                                                     [jar]
[WARNING] The POM for io.quarkus.platform:quarkus-maven-plugin:jar:3.4.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for io.quarkus.platform:quarkus-maven-plugin:3.4.0: Plugin io.quarkus.platform:quarkus-maven-plugin:3.4.0 or one of its dependencies could not be resolved: io.quarkus.platform:quarkus-maven-plugin:jar:3.4.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
[WARNING] The POM for org.apache.maven.plugins:maven-failsafe-plugin:jar:3.3.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-failsafe-plugin:3.3.0: Plugin org.apache.maven.plugins:maven-failsafe-plugin:3.3.0 or one of its dependencies could not be resolved: org.apache.maven.plugins:maven-failsafe-plugin:jar:3.3.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 9.8 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (21 kB at 14 kB/s)    
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Horreum 0.8-SNAPSHOT:
[INFO]
[INFO] Horreum ............................................ SKIPPED
[INFO] Horreum infra - common ............................. SKIPPED
[INFO] Horreum Dev Services - Parent ...................... SKIPPED
[INFO] Horreum Dev Services - Runtime ..................... SKIPPED
[INFO] Horreum Dev Services - Deployment .................. SKIPPED
[INFO] horreum-api ........................................ SKIPPED
[INFO] Horreum Backend .................................... SKIPPED
[INFO] Horreum Client ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.149 s
[INFO] Finished at: 2023-09-22T12:52:30+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'quarkus' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\shivam sharma\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by shivam-sharma7** [comment]
@jesperpedersen run ci again :)

**Comment by jesperpedersen** [comment]
Lets do this with #671 together

**Comment by jesperpedersen** [comment]
Did you look at

```
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] Running Quinoa package manager install command: node /home/jews/PostgreSQL/PerfTeam/Work/Horreum/official/webapp/node/node/node_modules/npm/bin/npm-cli.js install
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN ERESOLVE overriding peer dependency
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN While resolving: @apideck/better-ajv-errors@0.3.6
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN Found: ajv@6.12.6
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN node_modules/ajv
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   ajv@"^6.12.6" from the root project
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   6 more (@eslint/eslintrc, ajv-keywords, schema-utils, eslint, ...)
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN 
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN Could not resolve dependency:
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN peer ajv@">=8" from @apideck/better-ajv-errors@0.3.6
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN node_modules/@apideck/better-ajv-errors
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   @apideck/better-ajv-errors@"^0.3.1" from workbox-build@6.6.0
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   node_modules/workbox-build
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN 
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN Conflicting peer dependency: ajv@8.12.0
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN node_modules/ajv
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   peer ajv@">=8" from @apideck/better-ajv-errors@0.3.6
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   node_modules/@apideck/better-ajv-errors
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN     @apideck/better-ajv-errors@"^0.3.1" from workbox-build@6.6.0
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN     node_modules/workbox-build
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated @babel/plugin-proposal-private-methods@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] 
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] added 1506 packages, and audited 1507 packages in 18s
```

?

**Comment by shivam-sharma7** [comment]
@jesperpedersen I will look into but you don't forget that we are using quinoa for the webapp and I don't know why CI fail everytime but here in node never got error like this if I got then it's never break our project. They need to improve their CI. Here locally build got success

**Comment by johnaohara** [comment]
Have tested this locally and it looks good.  Before it is merged, we need to address the conflicting dependencies;

```

[INFO] Installing npm version 10.1.0
[INFO] Downloading https://registry.npmjs.org/npm/-/npm-10.1.0.tgz to D:\a\Horreum\Horreum\webapp\node\cache\npm-10.1.0.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] Unpacking D:\a\Horreum\Horreum\webapp\node\cache\npm-10.1.0.tar.gz into D:\a\Horreum\Horreum\webapp\node\node\node_modules
Warning:  [io.smallrye.openapi.runtime.scanner.spi] SROAP07903: Duplicate operationId: RunService_addRunFromData produced by Class: io.hyperfoil.tools.horreum.api.services.RunService, Method: jakarta.ws.rs.core.Response addRunFromData(java.lang.String, java.lang.String, java.lang.String, java.lang.String, io.hyperfoil.tools.horreum.api.data.Access, java.lang.String, java.lang.String, java.lang.String, java.lang.String) and Class: io.hyperfoil.tools.horreum.api.services.RunService, Method: jakarta.ws.rs.core.Response addRunFromData(java.lang.String, java.lang.String, java.lang.String, java.lang.String, io.hyperfoil.tools.horreum.api.data.Access, java.lang.String, java.lang.String, java.lang.String, org.jboss.resteasy.reactive.multipart.FileUpload, org.jboss.resteasy.reactive.multipart.FileUpload)
Warning:  [io.quarkus.deployment.steps.CombinedIndexBuildStep] Failed to index [Ljava.lang.String;: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD@2b9ede3d
[INFO] Installed npm locally.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] Running Quinoa package manager install command: node.exe D:\a\Horreum\Horreum\webapp\node\node\node_modules\npm\bin\npm-cli.js ci
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN ERESOLVE overriding peer dependency
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN While resolving: ajv-keywords@3.5.2
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN Found: ajv@8.12.0
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN node_modules/ajv
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   ajv@"^8.0.0" from the root project
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   13 more (@apideck/better-ajv-errors, ajv-formats, ajv-keywords, ...)
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN 
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN Could not resolve dependency:
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN peer ajv@"^6.9.1" from ajv-keywords@3.5.2
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN node_modules/ajv-keywords
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   ajv-keywords@"^3.5.2" from schema-utils@2.7.1
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   node_modules/babel-loader/node_modules/schema-utils
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   2 more (schema-utils, schema-utils)
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN 
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN Conflicting peer dependency: ajv@6.12.6
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN node_modules/ajv
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   peer ajv@"^6.9.1" from ajv-keywords@3.5.2
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN   node_modules/ajv-keywords
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN     ajv-keywords@"^3.5.2" from schema-utils@2.7.1
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN     node_modules/babel-loader/node_modules/schema-utils
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] npm WARN     2 more (schema-utils, schema-utils)
...
```

There is a new import for `"ajv": "^8.0.0",`, that is conflicting with `"react-scripts": "5.0.1"`, which pulls in ` ajv-keywords@"^3.5.2"` 

Unfortunately we can not upgrade react-scripts as it has not been released in over 2 years.  `"ajv": "^6.0.0",` is compatible with `ajv-keywords@"^3.5.2"` (take a look at: https://www.npmjs.com/package/ajv-keywords), so if we modify the import for ajv to `"ajv": "^6.12.6",` the conflicts are resolved.


After that change I think this is good to go.  We need to open a new issue to deal with the `react-scripts` issue, I don't think we should deal with that in this PR

**Comment by jesperpedersen** [comment]
Please, rebase

**Comment by shivam-sharma7** [comment]
done

**Comment by shivam-sharma7** [comment]
@jesperpedersen Done

**Comment by jesperpedersen** [comment]
I have merged the `husky` patch, but it is back again

**Comment by shivam-sharma7** [comment]
> I have merged the `husky` patch, but it is back again

I don't get it

**Comment by shivam-sharma7** [comment]
I think you were talking about husk dep.. in lock file

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Pull request merged**
