### PR TITLE
Upgrade keycloak

### PR DESCRIPTION
**Pull request by shivam-sharma7**
- upgrade keycloak version 
close: #435

### CODE REVIEW

**Comment by jesperpedersen** [comment]
You need more changes - `git grep keycloak`

**Comment by johnaohara** [comment]
@jesperpedersen is issue #435 to upgrade keycloak across the entire stack? If that is the case, we need to upgrade the projects that depend on horreum (e.g. jenkins plugin etc) as well to ensure API compatibility

**Comment by jesperpedersen** [comment]
And, we have to keep in mind the new management API for Keycloak

**Comment by jesperpedersen** [comment]
> You need more changes - `git grep keycloak`

Still true

**Pull request closed without merging**
