### PR TITLE
Node: Latest LTS Version: 20.9.0

### PR DESCRIPTION
**Pull request by shivam-sharma7**
let's try latest LTS node version in horreum I have downgrade npm version because on the top of the website they say this version include npm 10.1.0 check this-https://nodejs.org/en/download

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
rebased and pushed.

**Comment by shivam-sharma7** [comment]
@jesperpedersen please merge it!

**Comment by jesperpedersen** [comment]
No, we are focused on `0.10.x` - so we will wait

**Comment by shivam-sharma7** [comment]
then putting it as draft once that done I will or you can merge it.

**Comment by shivam-sharma7** [comment]
Q. @jesperpedersen How it will affect?

**Comment by jesperpedersen** [comment]
Shivam, you need to review your own patches.

There are 2 patches here...

1) The GitHub Action one
2) The node upgrade - but why is NPM downgraded ?

**Comment by shivam-sharma7** [comment]
@jesperpedersen 
> 1. The GitHub Action one
 I changes action/checkout@v3 to @v4 and build option was null so need to keep
> 2. The node upgrade - but why is NPM downgraded ?
actually they have said his in their chanellog to use that with this version and downgraded for 21.x
I hope you got it. So feel free to merge it.

**Comment by jesperpedersen** [comment]
I'm not taking this - you have to work upstream so this patch can be simpler

**Comment by shivam-sharma7** [comment]
> I'm not taking this - you have to work upstream so this patch can be simpler

What do you mean? please explain a bit more!

**Comment by jesperpedersen** [comment]
There is still an issue with npm...

**Comment by shivam-sharma7** [comment]
> There is still an issue with npm...

@jesperpedersen like what?

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Pull request merged**
