### PR TITLE
Combine: owner and access columns

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
I'm not able to import `./infra-legacy/example-configuration.sh` so it is a bit hard to see changes in UI

**Comment by jesperpedersen** [comment]
On `master` ? What are you seeing ?

**Comment by shivam-sharma7** [comment]
> On `master` ? What are you seeing ?

Yes, import fail

**Comment by jesperpedersen** [comment]
But why ?

**Comment by shivam-sharma7** [comment]
will report to you tommorow or after 17th oct

**Pull request closed without merging**
