### PR TITLE
Quarkus 3.8.4 upgrade

### PR DESCRIPTION
**Pull request by barreiro**

### CODE REVIEW

**Comment by barreiro** [comment]
test failures are likely caused by quarkusio/quarkus#39833 --- we may need to wait for a 3.8.4 release

**Comment by barreiro** [comment]
I can confirm that the integration tests pass with the fix for that issue

**Comment by stalep** [comment]
Quarkus 3.8.4 is planned for release on Wednesday 17th April including the fix needed

**Comment by johnaohara** [comment]
@willr3 do you mind reviewing this PR? you mentioned breaking changes in upgrading graalvm versions in https://github.com/Hyperfoil/Horreum/pull/1317#issuecomment-2064149403

**Pull request merged**
