### PR TITLE
replace switch with routes

### PR DESCRIPTION
**Pull request by shivam-sharma7**
close: #419

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Can you upgrade `react-router-dom` with this ?

**Comment by shivam-sharma7** [comment]
> Can you upgrade `react-router-dom` with this ?

mean version of `react-router-dom`?

**Comment by jesperpedersen** [comment]
Yes

**Comment by shivam-sharma7** [comment]
> Yes

 See this what @johnaohara said [#418](https://github.com/Hyperfoil/Horreum/pull/418#discussion_r1136468785)

**Comment by jesperpedersen** [comment]
```
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] Creating an optimized production build...
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] Failed to compile.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] 
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] Attempted import error: 'Routes' is not exported from 'react-router-dom' (imported as 'Routes').
```

**Comment by shivam-sharma7** [comment]
#421

**Comment by jesperpedersen** [comment]
```
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] Attempted import error: 'useHistory' is not exported from 'react-router-dom' (imported as 'useHistory').
```

**Comment by jesperpedersen** [comment]
```
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] Failed to compile.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] 
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] Attempted import error: 'Routes' is not exported from 'react-router-dom' (imported as 'Routes').
```

**Comment by jesperpedersen** [comment]
`localhost:8080` doesn't render the homepage anymore...

**Pull request closed without merging**
