### PR TITLE
README.md: now looks good

### PR DESCRIPTION
**Pull request by shivam-sharma7**
README.md: now looks good

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !

**Comment by johnaohara** [comment]
@jesperpedersen the hyperfoil logo wasn't designed for this project. We also have a design and pallete that has been through the legal process: https://design.jboss.org/hyperfoil/ & https://issues.redhat.com/browse/DESIGN-18440  We should refrain from creating our own logo design.

This also sparks another debate about whether Horreum should sit within the Hyperfoil repo, or be a seperate project. It sometimes causes confusion. I'll open a separate discussion

**Comment by johnaohara** [comment]
@shivam-sharma7 that logo was designed for a different tool: https://hyperfoil.io/

It is a bit confusing, but we were storing all the tools that we used with Hyperfoil under one repo. The tools themselves have now grown to such an extent that they should be split out into their own repos, with their own branding. 

We don't have any branding for Horreum at the moment

**Comment by shivam-sharma7** [comment]
okay John

**Pull request closed without merging**
