### PR TITLE
Combine: owner and access columns, fixes #404 #405 #428 #430

### LINKED ISSUE #404: AllTests.tsx: Combine "Owner" and "Access" columns
Combine "Owner" and "Access" columns into just an "Owner" column with show-cases the access padlock symbol

### PR DESCRIPTION
**Pull request by shivam-sharma7**
I followed our previous discusssion https://github.com/Hyperfoil/Horreum/pull/526#issue-1706915457

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Comment by shivam-sharma7** [comment]
I think this was best way to achieve that

**Comment by jesperpedersen** [comment]
Yes, that is why I approved it

**Comment by shivam-sharma7** [comment]
please, make sure all  related issue should be close.

**Comment by shivam-sharma7** [comment]
look at this one- https://github.com/Hyperfoil/Horreum/pull/827

**Pull request merged**
