### PR TITLE
DTO refactor, Horreum needs to separate between it's internal data model and the external

### PR DESCRIPTION
**Pull request by stalep**
- All the classes in -api have been replaced
- The horreum-model was moved into -backend
- Entities are now named EntityNameDAO
- Added mapper functionality located in -backend

### CODE REVIEW

**Comment by jesperpedersen** [comment]
I don't like EntityNameDAO at all - rename to EntityNameBean for now

**Comment by stalep** [comment]
> I don't like EntityNameDAO at all - rename to EntityNameBean for now

Can you explain why? I had a look at several resources and DAOs seemed to be recommended over Bean.

**Comment by jesperpedersen** [comment]
Its too close to DTO

**Comment by stalep** [comment]
> Its too close to DTO

We have nothing named DTO so there should not be any confusion.

**Comment by jesperpedersen** [comment]
Well, we can't call them EJB...

The default name for an Entity should be the name of the object itself - so EntityName - doing `@Table()` is just weird. Ideally the entire model would be locked in by the database and the application layer would have to adapt to that. That way DBAs to use database native functionality to optimize such as partitioning.

An Entity is def not a DTO - since that is a representation on a wire. And, since DAO is too close IMHO it is a no go.

**Comment by jesperpedersen** [comment]
Rebased, and merge - due the Gang of Four.

Thanks for your contribution !

**Pull request closed without merging**
