### PR TITLE
enabled disabled tests

### PR DESCRIPTION
**Pull request by stalep**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jesperpedersen** [comment]
This fails locally even with increased like the attached patch

[timeout.txt](https://github.com/Hyperfoil/Horreum/files/13043739/timeout.txt)

**Comment by jesperpedersen** [comment]
```
[ERROR] Tests run: 15, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 25.769 s <<< FAILURE! - in io.hyperfoil.tools.horreum.svc.AlertingServiceTest
[ERROR] io.hyperfoil.tools.horreum.svc.AlertingServiceTest.testLabelsChange(TestInfo)  Time elapsed: 10.257 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: not <null>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:30)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:301)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceTest.testLabelsChange(AlertingServiceTest.java:700)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

```
[ERROR] Tests run: 13, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 23.28 s <<< FAILURE! - in io.hyperfoil.tools.horreum.svc.DatasetServiceTest
[ERROR] io.hyperfoil.tools.horreum.svc.DatasetServiceTest.testDatasetLabelChanged  Time elapsed: 10.32 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: not <null>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:30)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:301)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceTest.waitForUpdate(DatasetServiceTest.java:397)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceTest.lambda$testDatasetLabelChanged$46(DatasetServiceTest.java:210)
	at io.hyperfoil.tools.horreum.svc.BaseServiceTest.withExampleDataset(BaseServiceTest.java:591)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceTest.lambda$testDatasetLabelChanged$47(DatasetServiceTest.java:199)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceTest.withExampleSchemas(DatasetServiceTest.java:366)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceTest.testDatasetLabelChanged(DatasetServiceTest.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

```
[ERROR] io.hyperfoil.tools.horreum.svc.DatasetServiceTest.testSchemaAfterData  Time elapsed: 10.134 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: not <null>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:30)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:301)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceTest.testSchemaAfterData(DatasetServiceTest.java:263)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.909 s <<< FAILURE! - in io.hyperfoil.tools.horreum.svc.SchemaServiceTest
[ERROR] io.hyperfoil.tools.horreum.svc.SchemaServiceTest.testValidateRun  Time elapsed: 10.149 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: not <null>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:30)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:301)
	at io.hyperfoil.tools.horreum.svc.SchemaServiceTest.testValidateRun(SchemaServiceTest.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by jesperpedersen** [comment]
I have

```
2023-10-19 11:42:08,993 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16201: AMQP broker configured to localhost:43973 for channel dataset-event-in
2023-10-19 11:42:09,011 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16201: AMQP broker configured to localhost:43973 for channel run-recalc-in
2023-10-19 11:42:09,012 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16201: AMQP broker configured to localhost:43973 for channel dataset-event-out
2023-10-19 11:42:09,017 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16201: AMQP broker configured to localhost:43973 for channel run-recalc-out
2023-10-19 11:42:09,034 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16212: Establishing connection with AMQP broker
2023-10-19 11:42:09,038 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16212: Establishing connection with AMQP broker
2023-10-19 11:42:09,044 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16212: Establishing connection with AMQP broker
2023-10-19 11:42:09,045 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16212: Establishing connection with AMQP broker
2023-10-19 11:42:09,101 INFO  [io.quarkus] (main) horreum-backend 0.10-SNAPSHOT on JVM (powered by Quarkus 3.4.3) started in 18.585s. Listening on: http://localhost:8081
2023-10-19 11:42:09,102 INFO  [io.quarkus] (main) Profile test activated. 
2023-10-19 11:42:09,102 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-postgresql, liquibase, mailer, narayana-jta, oidc, quinoa, qute, reactive-pg-client, rest-client, rest-client-jackson, rest-client-jaxb, resteasy-reactive, resteasy-reactive-jackson, scheduler, security, smallrye-context-propagation, smallrye-openapi, smallrye-reactive-messaging, smallrye-reactive-messaging-amqp, swagger-ui, vertx]
2023-10-19 11:42:09,291 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-1) SRMSG16213: Connection with AMQP broker established
2023-10-19 11:42:09,311 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-1) SRMSG16213: Connection with AMQP broker established
2023-10-19 11:42:09,321 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-1) SRMSG16213: Connection with AMQP broker established
2023-10-19 11:42:09,324 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-1) SRMSG16213: Connection with AMQP broker established
2023-10-19 11:42:09,374 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-1) SRMSG16203: AMQP Receiver listening address dataset-event
2023-10-19 11:42:09,383 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-1) SRMSG16203: AMQP Receiver listening address run-recalc
```

in the log...

**Comment by stalep** [comment]
It looks like they all fail for you for the logic where we use the queue.
I can see that the CI works so it might be something locally. Can you put a breakpoint at ServiceMediator line 144 to verify that you're actually getting messages out?

**Comment by jesperpedersen** [comment]
https://github.com/Hyperfoil/Horreum/pull/773/files#diff-d0bb8e16a2504f8c9d5886a99c4800c221bd4c8e47c67eec49a2e9b9d648aac9R191 so some of the tests are disabled in CI

**Comment by stalep** [comment]
Yes, since they are not reliably passing, but I have the tests passing on both the desktop and laptop. Not sure what else I can think of. Did you try to set a breakpoint?

**Comment by stalep** [comment]
Desktop is with docker and laptop with podman so that should not make a difference.

**Comment by jesperpedersen** [comment]
I'm getting

```
[ERROR] Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.513 s <<< FAILURE! - in io.hyperfoil.tools.horreum.svc.DatasetServiceTest
[ERROR] io.hyperfoil.tools.horreum.svc.DatasetServiceTest.testSchemaAfterData  Time elapsed: 0.215 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <0> but was: <98>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceTest.testSchemaAfterData(DatasetServiceTest.java:275)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

with `docker-ce-24.0.6-1.fc38.x86_64` and
```
postgres                                       13        5287b99d8815   2 months ago   405MB
```

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !

**Pull request closed without merging**
