### PR TITLE
Remove db encryption with pgcrypto

### PR DESCRIPTION
**Pull request by barreiro**
Fixes: #779

### CODE REVIEW

**Comment by johnaohara** [comment]
@barreiro has there been any further progress on this? thanks

**Comment by johnaohara** [comment]
@barreiro the integration tests run with a built jar and therefore runs in prod mode by default.  We either need to enable ssl in the postgres container or do not enable by default for prod in `application.properties` and make sure it is highlighted in to docs that it is recommended to enable TLS in production.

I do not think creating and registering a self-signed cert for integration test will be simple

**Comment by johnaohara** [comment]
@barreiro please can you squash commits

**Comment by johnaohara** [comment]
LGTM, please squash and I will merge, thanks!

**Comment by barreiro** [comment]
rebased and squashed

**Pull request merged**
