### PR TITLE
Downgrade Keycloak to 23.0.7

### PR DESCRIPTION
**Pull request by johnaohara**
Keycloak version was incompatible with services running SSO

## Fixes Issue

Fixes: #2061

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by lampajr — CHANGES_REQUESTED** [review]
Hey @johnaohara, I am not 100% sure but I think that we are still bringing `25.0.2` version for keycloak (in some places):

```

[INFO] \- io.quarkus:quarkus-keycloak-admin-resteasy-client:jar:3.14.4:compile
....
[INFO]    +- org.keycloak:keycloak-admin-client:jar:25.0.2:compile
```

That's might be the reason of the failure we see here.

**Comment by johnaohara** [comment]
either we need to remove the dependency on `quarkus-keycloak-admin-resteasy-client` or only use Quarkus LTS releases

**Comment by lampajr** [comment]
> it's a mess after we upgraded quarkus :(

+1

> either we need to remove the dependency on quarkus-keycloak-admin-resteasy-client 

I was trying this locally, but even if that works for the test I am not fully sure we won't introduce any bug by forcing  `quarkus-keycloak-admin-resteasy-client` to use an older version of keycloak

> only use Quarkus LTS releases

I think this will be something we should start considering..

**Comment by lampajr** [comment]
> either we need to remove the dependency on `quarkus-keycloak-admin-resteasy-client` or only use Quarkus LTS releases

Both options are not so straightforward.. :sweat:

**Comment by johnaohara** [comment]
@lampajr i saw this error when re-using a prod backup that had been loaded in dev mode by current main or 0.15 branch.  When I tested with a fresh backup it worked without error.

I think the with the current main branch, upgrading to keycloak 0.25.x will have modified the database tables, which are incompatible with 0.23.x, so downgrading keycloak on an already migrated database will break auth.

We need to be able to chose the keycloak version to maintain compatibility with production versions

**Review by lampajr — APPROVED** [review]
lgtm then!

**Pull request merged**
