### PR TITLE
Removed the unused profile and resource.

### PR DESCRIPTION
**Pull request by whitingjr**
## Fixes Issue

Related to #2039 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by lampajr — COMMENTED** [review]
Interesting, in my local environment one test is failing after this change:
```bash
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.170 s <<< FAILURE! -- in io.hyperfoil.tools.horreum.svc.UtilTest
[ERROR] io.hyperfoil.tools.horreum.svc.UtilTest.evaluateOnceAsyncAwaitFetchJson -- Time elapsed: 0.013 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Cannot assign requested address
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at io.hyperfoil.tools.horreum.svc.UtilTest.evaluateOnceAsyncAwaitFetchJson(UtilTest.java:248)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   UtilTest.evaluateOnceAsyncAwaitFetchJson:248 Cannot assign requested address
[INFO] 
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0
```

@whitingjr are you experiencing the same in your local env?

**Comment by whitingjr** [comment]
> @whitingjr are you experiencing the same in your local env?

When I tested it yesterday I did not.
I'll try again and make sure to clean the workspace beforehand.

**Comment by whitingjr** [comment]
Just tested again and the tests passed.
```
$ mvn  test -Dtest=UtilTest -Dsurefire.failIfNoSpecifiedTests=false
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.hyperfoil.tools.horreum.svc.UtilTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.808 s -- in io.hyperfoil.tools.horreum.svc.UtilTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

```
 The http server is started on an ephemeral port. Were you just unlucky getting a collision and another attempt passes ?

**Comment by lampajr** [comment]
> Were you just unlucky getting a collision and another attempt passes ?

it seems deterministic in my case, I was not able to get it working yet.. it keeps failing on every attempt :cry:

**Comment by lampajr** [comment]
I was able to get it working but I had to change the server initialization to:
```java
httpServer = HttpServer.create(new InetSocketAddress(0), 0);
```

i.e., removing the hostname

**Comment by johnaohara** [comment]
> Interesting, in my local environment one test is failing after this change:
> 
> ```shell
> [ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.170 s <<< FAILURE! -- in io.hyperfoil.tools.horreum.svc.UtilTest
> [ERROR] io.hyperfoil.tools.horreum.svc.UtilTest.evaluateOnceAsyncAwaitFetchJson -- Time elapsed: 0.013 s <<< FAILURE!
> org.opentest4j.AssertionFailedError: Cannot assign requested address
> 	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
> 	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
> 	at io.hyperfoil.tools.horreum.svc.UtilTest.evaluateOnceAsyncAwaitFetchJson(UtilTest.java:248)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 
> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Failures: 
> [ERROR]   UtilTest.evaluateOnceAsyncAwaitFetchJson:248 Cannot assign requested address
> [INFO] 
> [ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0
> ```
> 
> @whitingjr are you experiencing the same in your local env?

@willr3 is this a test for a feature we are not supporting in Horreum atm? can we disable it?

**Comment by willr3** [comment]
UtilTest.evaluateOnceAsyncAwaitFetchJson is a test that ensures async functions do not execute fetch

**Comment by johnaohara** [comment]
> UtilTest.evaluateOnceAsyncAwaitFetchJson is a test that ensures async functions do not execute fetch

Ok, so we need to make sure it works in all environments, or at least understand why the current impl does not work in @lampajr environment

**Comment by lampajr** [comment]
> Ok, so we need to make sure it works in all environments, or at least understand why the current impl does not work in @lampajr environment

Not sure what is actually not working and why yet, but with the change I shared here https://github.com/Hyperfoil/Horreum/pull/2058#issuecomment-2393530460 I can confirm it works which is good

**Comment by whitingjr** [comment]
@lampajr can you share basic details (platform, version, jdk version) of your system ?

**Comment by lampajr** [comment]
> @lampajr can you share basic details (platform, version, jdk version) of your system ?

```bash
$ cat /etc/redhat-release
Fedora release 40 (Forty)

$ java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)
```

**Review by lampajr — APPROVED** [review]
Ok looks like it is working now, don't know what was wrong the last time 🫤 

LGTM @whitingjr!

**Pull request merged**
