### PR TITLE
docs: add contributor list

### PR DESCRIPTION
**Pull request by shivam-sharma7**
docs: add contributor list

### CODE REVIEW

**Comment by jesperpedersen** [comment]
This needs to be an `AUTHORS` file with name and email

**Comment by shivam-sharma7** [comment]
> This needs to be an `AUTHORS` file with name and email

I think no need. it is work, you can see output in following image

Screenshot 2023-02-09 221715

**Comment by jesperpedersen** [comment]
We can do the `AUTHORS` file as a separate PR.

You need to rebase your pull requests.

Rebased, and merged.

Thanks for your contribution !

**Comment by shivam-sharma7** [comment]
hi, @jesperpedersen 

you mean i need to create new file for `AUTHURS`. do i have to rebase this PR?

**Comment by jesperpedersen** [comment]
You don't have to create it - but you can :)

You need to make sure that your pull requests are up-to-date against the latest `master`, so look at how to do that - f.ex. in the ProGit book.

**Comment by shivam-sharma7** [comment]
Okay Thanks for the suggestion! :)

**Pull request merged**
