### PR TITLE
Migration react-router-dom 5 to 6

### PR DESCRIPTION
**Pull request by shivam-sharma7**
Migration react-router-dom 5 to v6 

fixes: #723

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
let see build passed?

**Comment by shivam-sharma7** [comment]
@johnaohara I have first priority for this instead -> #982

**Review by johnaohara — CHANGES_REQUESTED** [review]
The issues that I have noted need to be fixed before we can fully test the UI

**Comment by shivam-sharma7** [comment]
@johnaohara If you have any suggetion on this problem then let me know?

**Comment by shivam-sharma7** [comment]
@johnaohara rebased

**Review by johnaohara — APPROVED** [review]

**Pull request merged**
