### PR TITLE
Pagination for AllTest 

### PR DESCRIPTION
**Pull request by shivam-sharma7**
fixes: #387

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@johnaohara This is our main issue-https://github.com/Hyperfoil/Horreum/actions/runs/5868853578/job/15912575614?pr=621#step:6:484

**Comment by johnaohara** [comment]
@shivam-sharma7 I just pushed this change: https://github.com/Hyperfoil/Horreum/pull/621/commits/7b4f234d875839c223b83f2cec2818b721e1b2f8

**Comment by shivam-sharma7** [comment]
@Thanks CI green!

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !

**Pull request closed without merging**
