### PR TITLE
docs: update local development

### PR DESCRIPTION
**Pull request by shivam-sharma7**
docs: update local development

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Please, look into how to rebase against `master` so we don't have merge commits.

**Comment by shivam-sharma7** [comment]
hi,
But before creating any new branch or  PR I always first keep update my `origin master` with `upstream master` if there is some thing. please you can tell me.

**Comment by jesperpedersen** [comment]
Yeah, because `master` can change at any point during your development

**Comment by shivam-sharma7** [comment]
i mostly use `git rebase`

**Pull request merged**
