### PR TITLE
Remove unused object from vite.config.ts

### PR DESCRIPTION
**Pull request by shivam-sharma7**
We are not using this from long time and it is done by quarkus so Removing this.

 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
> This was added because vite was automatically opening a browser tab to the node dev url. Are you saying vite no longer automatically opens a browser tab by default?

No, I mean once our application start then we can access `3000` port and we don't need to do `npm run dev` to open this.

**Comment by willr3** [comment]
I think your PR is trying to remove a change that was intentionally introduced to prevent view from opening a browser tab.

**Comment by shivam-sharma7** [comment]
> I think your PR is trying to remove a change that was intentionally introduced to prevent vite from opening a browser tab.

Yeah, for sure and I think we don't need it.

**Comment by johnaohara** [comment]
the `open` property appears defaults to false, removing this property retains the current behaviour

**Pull request merged**
