### PR TITLE
Add Go to Home Button

### PR DESCRIPTION
**Pull request by shivarm**
image

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@jesperpedersen I rebased and pushed. I think now its looking cool:)

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Comment by shivam-sharma7** [comment]
@jesperpedersen I forgot to add `hover` should we add hover effect?

**Comment by shivam-sharma7** [comment]
I can open a PR for this

**Comment by jesperpedersen** [comment]
Nah, it is ok for now

**Pull request merged**
