### PR TITLE
Replace Quinoa link in README.md #501

### PR DESCRIPTION
**Pull request by rukundob451**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by shivam-sharma7 — CHANGES_REQUESTED** [review]
Remove [doc/Windows.md](https://github.com/Hyperfoil/Horreum/pull/504/files#diff-9e5c71d02b6ce8fce8adf0b6a15b498cf7768cad42310ce53dde4adb9a06308f) file

**Comment by rukundob451** [comment]
> Remove [doc/Windows.md](https://github.com/Hyperfoil/Horreum/pull/504/files#diff-9e5c71d02b6ce8fce8adf0b6a15b498cf7768cad42310ce53dde4adb9a06308f) file

Should I just delete it, am not seeing option to remove?

**Comment by shivam-sharma7** [comment]
> > Remove [doc/Windows.md](https://github.com/Hyperfoil/Horreum/pull/504/files#diff-9e5c71d02b6ce8fce8adf0b6a15b498cf7768cad42310ce53dde4adb9a06308f) file
> 
> Should I just delete it, am not seeing option to remove?

Remember you need to squash your commits!

There is a couple of ways to do this in `git` but you can delete it and commit again.

**Comment by rukundob451** [comment]
> > > Remove [doc/Windows.md](https://github.com/Hyperfoil/Horreum/pull/504/files#diff-9e5c71d02b6ce8fce8adf0b6a15b498cf7768cad42310ce53dde4adb9a06308f) file
> > 
> > 
> > Should I just delete it, am not seeing option to remove?
> 
> Remember you need to squash your commits!
> 
> There is a couple of ways to do this in `git` but you can delete it and commit again.

@shivam-sharma7 kindly checkout, I think I have done this.

**Comment by jesperpedersen** [comment]
If you look at the pull request you can see 7 commits, and the files changed.

F.ex. here you removed `doc/Windows.md`.

https://git-scm.com/book/en/v2

**Comment by shivam-sharma7** [comment]
@rukundob451 Open another PR and Remember don't make changes ` doc/Windows.md`

**Comment by shivam-sharma7** [comment]
#501

**Comment by jesperpedersen** [comment]
@rukundob451 Please, work on this, and you can use this pull request. Just force push the branch once you have the correct changes

**Comment by rukundob451** [comment]
> @rukundob451 Please, work on this, and you can use this pull request. Just force push the branch once you have the correct changes

Alright @jesperpedersen working on this currently, thank you.

**Pull request closed without merging**
