### PR TITLE
AllSchema.tsx: Combine

### PR DESCRIPTION
**Pull request by shivam-sharma7**
AllSchema.tsx: Combine "Owner" and "Access" columns

close: #405

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
review/ @jesperpedersen

**Comment by jesperpedersen** [comment]
Can you remove the whitespace changes ?

However, it doesn't look like you have implemented the issue... It currently looks like

```
| Owner | Access |
| MyAccount | Public <black padlock> |
```

and it needs to look as

```
| Owner |
| MyAccount  <black padlock> |
```

instead

**Comment by jesperpedersen** [comment]
(If you are looking to reindent the .tsx files - then do a separate pull request where you do them all at once with a dedicated style)

**Comment by jesperpedersen** [comment]
```
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] Type 'Access | null' is not assignable to type 'string | undefined'.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager]   Type 'null' is not assignable to type 'string | undefined'.  TS2322
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] 
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager]     48 |                       <div>
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager]     49 |                         <span>{teamToName(owner)}</span>{" "}
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager]   > 50 |                         <span title={access} style={{ color: "black" }}>
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager]        |                               ^
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager]     51 |                           <AccessIcon access={access} />
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager]     52 |                         </span>
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager]     53 |                       </div>
```

And, `AccessIcon` has the text - see https://github.com/Hyperfoil/Horreum/pull/411#issuecomment-1464824431

**Pull request closed without merging**
