### PR TITLE
MPL-75: Establish schemas team selector

### PR DESCRIPTION
**Pull request by lampajr**
## Fixes Issue

Fixes https://github.com/Hyperfoil/Horreum/issues/1589

## Changes proposed

- [x] Re-establish the schemas filter by team from the UI (that was hidden as part of https://github.com/Hyperfoil/Horreum/pull/1290 because not properly implemented)
- [x] Implemented schemas filtering by roles (i.e., team selection), the same way it is implemented on tests side 
- [x] Improve some test cases for both tests and schemas (focusing on this team filtering)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lampajr** [comment]
Keeping in draft as it depends on https://github.com/Hyperfoil/Horreum/pull/1600, once that can be merged I will rebase this PR on top of `master`

**Comment by lampajr** [comment]
As https://github.com/Hyperfoil/Horreum/pull/1600 got merged, I rebased this PR on top of `master` branch.

**Review by willr3 — COMMENTED** [review]
Everything looks good to me.

**Comment by johnaohara** [comment]
@willr3 @lampajr are we good to merge this?

**Comment by willr3** [comment]
@johnaohara yes it looks good to merge, didn't know if this was pre or post 0.13 as I didn't see milestones when I checked

**Comment by johnaohara** [comment]
Thanks a lot, the milestone was on the issue, otherwise it appears twice in the milestone planning

**Pull request merged**
