### PR TITLE
Support Docker Desktop for building native executables with quarkus 3.6.0

### PR DESCRIPTION
**Pull request by shivam-sharma7**
Support Docker Desktop for building native executables with quarkus 3.6.0
The @Blocking annotations validation are new in Quarkus 3.6.0

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@johnaohara Thanks

**Comment by johnaohara** [comment]
@shivam-sharma7 : we still need the `@Blocking` annotation, but it needs to be defined on the interface methods, instead of the concrete class: https://github.com/shivam-sharma7/Horreum/blob/quarkus/horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java#L25

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 : we still need the `@Blocking` annotation, but it needs to be defined on the interface methods, instead of the concrete class: https://github.com/shivam-sharma7/Horreum/blob/quarkus/horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java#L25

@johnaohara I'm thinking to do that in a seprate PR!

**Comment by johnaohara** [comment]
> @johnaohara I'm thinking to do that in a seprate PR!

It needs to be in this PR, we can't intentionally break the threading model

**Comment by shivam-sharma7** [comment]
rebased against the `master`

**Comment by shivam-sharma7** [comment]
@jesperpedersen have a look

**Comment by shivam-sharma7** [comment]
@johnaohara should I open PR against the `10.x` for backport

**Pull request merged**
