### PR TITLE
fix 1336 with corrected start and stop annotations

### PR DESCRIPTION
**Pull request by willr3**
Should generate a corrected openapi.yaml. We should also look at testing the generated openapi.yaml with all endpoints?

closes: #1336

### CODE REVIEW

**Comment by stalep** [comment]
We should have a look at how we format date/time in Horreum. In TestService.listLabelValues we use strings as the type, but we accept either iso-like or epoch. I think the intention was to default to that, but it has not been communicated well.

**Comment by willr3** [comment]
`TestService.listLabelValues` supports different time formats for the `before` and `after` query parameters to make it easier for users to request data from Horreum. The issue this addresses is how we describe the data that Horreum provides.

When Horreum encodes an `Instant` into json it is currently encoded as a `Long` but the annotations told openapi to create an `openapi.yaml` that claims the values will be an ISO style string. The PR changes the annotations to match the data type Horreum is already using.

We can discuss if `Long` or an ISO `String` is more appropriate for integration with other tools but for now this PR is a bug fix for incorrect annotations.

**Review by webbnh — APPROVED** [review]
Looks good to me.

**Comment by johnaohara** [comment]
This PR is missing the changes to `openapi.yaml`. Please can we ensure that if we change the openapi annotations, that the corresponding generated `openapi.yaml` is also checked in with the PR otherwise what we publish on the website is out of sync with the actual API

**Pull request merged**
