### PR TITLE
removed json properties on DAO objects, had to annotate some with Jso…

### PR DESCRIPTION
**Pull request by stalep**
…nIgnoreType to prevent Jackonmapper to run wild

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by stalep** [comment]
To prevent Jackson to go wild (recursive) I had to add JsonIgnoreType on several of the DAOs.
Also, with this change the AlertingServiceTest.testChangeDetection:166->testSerialization:206 fails to deserialize the ChangeDAO.Event object as Jackson is no longer scanning it (this is what I assume happens).

So, either we change the MessageBus to use Change.Event objects instead or we need to wait with this refactor until we've refactored the MessageBus.

**Comment by stalep** [comment]
The second commit fixes the test issues

**Comment by jesperpedersen** [comment]
Move it out of draft once you are ready for a review

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !

**Pull request closed without merging**
