### PR TITLE
rename DataSet to Dataset and DataSetDAO to DatasetDAO to be consistent

### PR DESCRIPTION
**Pull request by stalep**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jesperpedersen** [comment]
```
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner] TS2551: Property 'datasetServiceGetDataSet' does not exist on type 'DefaultApi'. Did you mean 'datasetServiceGetDataset'?
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]     34 |     const [experimentsOpen, setExperimentsOpen] = useState(false)
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]     35 |     useEffect(() => {
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]   > 36 |         Api.datasetServiceGetDataSet(props.datasetId)
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]        |             ^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]     37 |             .then(
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]     38 |                 dataset => {
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]     39 |                     setOriginalData(dataset.data)
```

**Comment by jesperpedersen** [comment]
Maybe as part of this we should look at `git grep ataSet` such it is the same all over...

**Comment by stalep** [comment]
> Maybe as part of this we should look at `git grep ataSet` such it is the same all over...

I do not think we need to change variable names, I've renamed the test names that used DataSet now so all methods and classes are renamed.

**Comment by jesperpedersen** [comment]
I'm working on this...

**Comment by jesperpedersen** [comment]
Conflicts resolved, rebased and merged.

Thanks for your contribution !

**Pull request closed without merging**
