### PR TITLE
Combine: owner and access columns

### PR DESCRIPTION
**Pull request by shivam-sharma7**
Combine: owner and access columns AllTests.tsx
Combine: owner and access columns AllSchema.tsx
Combine: owner and access columns TestRuns.tsx
Combine: owner and access columns TestDatasets.tsx

 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jesperpedersen** [comment]
We need a new component such that "Public" / "Private" isn't displayed

**Comment by shivam-sharma7** [comment]
> We need a new component such that "Public" / "Private" isn't displayed

I don't understand

**Comment by shivam-sharma7** [comment]
> before
> 
> to
> 
> after

@jesperpedersen I want to know how you able to see this in live, here I can't see.

**Comment by shivam-sharma7** [comment]
image

@jesperpedersen currently Ui not visible

**Pull request closed without merging**
