### PR TITLE
[0.11.x] Fix conflicting npm dependencies and bump typescript 4 to 5

### PR DESCRIPTION
**Pull request by johnaohara**
**Backport:** https://github.com/Hyperfoil/Horreum/pull/1224

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@johnaohara We need to regenerate `package-lock.json`

steps
1. Delete old `package-lock.json`
2. Run `npm i` in Horreum-web
3. force push

**Comment by johnaohara** [comment]
> @johnaohara We need to regenerate `package-lock.json`
> 
> steps
> 
> 1. Delete old `package-lock.json`
> 2. Run `npm i` in Horreum-web
> 3. force push

yeah, package-lock is becoming a massive pain point for us, I need to think about ways of handling it so we are not being constantly affected by conflicts and having to rebuild

**Comment by shivam-sharma7** [comment]
Ci failure look a npm issue-https://github.com/Hyperfoil/Horreum/actions/runs/7764614586/job/21178269891?pr=1241#step:6:619

see discussions and solution on the issue-https://github.com/npm/cli/issues/4828#issuecomment-1909795232

> yeah, package-lock is becoming a massive pain point for us, I need to think about ways of handling it so we are not being constantly affected by conflicts and having to rebuild

we have to stop dependabot for `npm dependencies` now

**Comment by shivam-sharma7** [comment]
I have not access of this otherwise i can try to fix it in my env

**Comment by johnaohara** [comment]
I don't think dependabot is the cause of this issue, I built the package-lock.json on my Mac, which is currently using npm 9.5.0

I think a lot of our problems are coming from different versions of node/npm in different environments. I think we need to consider using a consistent env (possibly CI) to build package-lock.json for us

**Comment by shivam-sharma7** [comment]
> I don't think dependabot is the cause of this issue, I built the package-lock.json on my Mac, which is currently using npm 9.5.0
> 

Yeah, It is.

> I think a lot of our problems are coming from different versions of node/npm in different environments. I think we need to consider using a consistent env (possibly CI) to build package-lock.json for us

Then let's keep current node/npm versions which is used by horreum, in local as well so I have this already and I think you have to follow this.

**Comment by johnaohara** [comment]
> > I don't think dependabot is the cause of this issue, I built the package-lock.json on my Mac, which is currently using npm 9.5.0
> 
> Yeah, It is.
> 
Could you explain why you think dependabot is the issue?

**Comment by johnaohara** [comment]
@shivam-sharma7 I think we should take the package-lock.json chat to a discussion

**Comment by shivam-sharma7** [comment]
> Could you explain why you think dependabot is the issue?

as @jesperpedersen said-https://github.com/Hyperfoil/Horreum/issues/587#issuecomment-1630863622

**Pull request merged**
