### PR TITLE
[434] Run Ci on Ubuntu and Windows environments

### PR DESCRIPTION
**Pull request by johnaohara**

### CODE REVIEW

**Comment by johnaohara** [comment]
@jesperpedersen do we want to leave this as draft until we have fixed the windows build problem? otherwise all our PR's will fail until we fix the windows build problem

**Comment by jesperpedersen** [comment]
Yeah, lets keep it in draft mode atm

**Comment by johnaohara** [comment]
I have jobs completing on Windows, with some major caveats: https://github.com/johnaohara/Horreum/actions/runs/4447380941

The jobs builds but;

- I can not run tests on windows. At present docker operations is not supported on Windows runners: https://github.com/actions/runner/issues/904
- The client is not compiling on Windows.  This is likely due to the API JSON obj generation not working as expected in a Win env, but without a windows dev machine I can not investigate further

So, is running a windows CI something we want to do atm given the limitations? we can verify it at least builds, but we can test the build right now

**Comment by jesperpedersen** [comment]
Lets merge what we have atm

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !

**Comment by jesperpedersen** [comment]
@shivam-sharma7 Can you see what this does to your WSL2 env...

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 Can you see what this does to your WSL2 env...

Okay @jesperpedersen

**Comment by shivam-sharma7** [comment]
when i run `npm start` UI looks like this. Is this UI?

image

**Comment by jesperpedersen** [comment]
@shivam-sharma7 Do you have `infra/` running with https://github.com/Hyperfoil/Horreum#example-configuration ?

**Comment by jesperpedersen** [comment]
@shivam-sharma7 Please, raise a new discussion in the forum with the details

**Comment by shivam-sharma7** [comment]
okay

**Comment by johnaohara** [comment]
@shivam-sharma7 there are still issues building some of the modules on Windows, please can you retry running the application with adding the following parameters `"-Dquarkus.container-image.build=false" -pl '!horreum-client, !horreum-integration' -DskipITs -DskipTests`

**Comment by shivam-sharma7** [comment]
I think we should setup a meeting @johnaohara @jesperpedersen.

**Pull request closed without merging**
