### PR TITLE
destructure component

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@jesperpedersen I think now all windows doc remove by @johnaohara now how can i set up this project using docker

**Comment by johnaohara** [comment]
@shivam-sharma7 if you follow the README, it should work in Windows. You start docker desktop in wondpws and then run the commands here: https://github.com/Hyperfoil/Horreum#getting-started-with-development-server

You do not need to use WSL and can now just use powershell to start the dev server

**Comment by shivam-sharma7** [comment]
> > @shivam-sharma7 if you follow the README, it should work in Windows. You start docker desktop in windows and then run the commands here: https://github.com/Hyperfoil/Horreum#getting-started-with-development-server
> 
> @johnaohara  How we are running docker containers here?: https://github.com/Hyperfoil/Horreum#getting-started-with-development-server

**Comment by johnaohara** [comment]
> https://github.com/Hyperfoil/Horreum#getting-started-with-development-server

you do not need to start any containers manually, 'mvn' starts/stops and configures all the containers for you automatically

**Pull request merged**
