### PR TITLE
[#390] AllSchema sort by name

### PR DESCRIPTION
**Pull request by shivam-sharma7**
close: #390

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
review/ @jesperpedersen

**Comment by jesperpedersen** [comment]
The default sort order should be "Name : Ascending"

**Comment by shivam-sharma7** [comment]
> 

your mean?

**Comment by jesperpedersen** [comment]
The table needs to be sorted by default on the `Name` column - so the `sortBy` property needs to be set, and `Name` needs to be a valid default sort column.

Look at `webapp/src/domain/runs/TestRuns.tsx` for ideas.

**Comment by shivam-sharma7** [comment]
> The table needs to be sorted by default on the `Name` column - so the `sortBy` property needs to be set, and `Name` needs to be a valid default sort column.
> 
> Look at `webapp/src/domain/runs/TestRuns.tsx` for ideas.
Thanks

**Comment by shivam-sharma7** [comment]
> I don't see the sorting being active...

 Hey @jesperpedersen review this code.

import { useTable, Column, useSortBy } from 'react-table';
 
``` 
    {
    Header: 'Name',
    accessor: 'name',
    sortDescFirst: false,
    Cell: (arg: C) => {
      return <NavLink to={`/schema/${arg.row.original.id}`}>{arg.cell.value}</NavLink>;
    },
  },
  {
    Header: 'URI',
    accessor: 'uri',
  },
  {
    Header: 'Description',
    accessor: 'description',
  },
  {
    Header: 'Owner',
    accessor: 'owner',
    Cell: (arg: C) => teamToName(arg.cell.value),
  },
  {
    Header: 'Access',
    accessor: 'access',
    Cell: (arg: C) => <AccessIcon access={arg.cell.value} />,
  },
         
Is this following nees to implement?

// define data and options
const data: Schema[] = ...; // your array of schema objects
const options = { initialState: { sortBy: [{ id: 'name', desc: false }] } };

// create table instance
const tableInstance = useTable({ columns, data, options }, useSortBy);

// extract required properties
const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow } = tableInstance;
````

**Comment by jesperpedersen** [comment]
Can you update the pull request with this ?

**Pull request closed without merging**
