### PR TITLE
Fix failing CI tests

### PR DESCRIPTION
**Pull request by johnaohara**

### CODE REVIEW

**Comment by johnaohara** [comment]
@jesperpedersen If this works on CI (it is working locally for me), it will supersede https://github.com/Hyperfoil/Horreum/pull/817

**Comment by johnaohara** [comment]
that is disappointing, 

all tests pass on my desktop, and mac m2 laptop, still got failures in CI

**Comment by johnaohara** [comment]
OK, first green light. 2 races conditions have been fixed so far, still looks like there is one lurking that hasn't caused any of the tests to fail

**Comment by shivam-sharma7** [comment]
@jesperpedersen I have seen that this PR changes make CI execution a bit fast!

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !

**Pull request closed without merging**
