### PR TITLE
Fix UI fingerprint mappings - 

### LINKED ISSUE #867: Fingerprints not rendering correctly in `Changes` view
The Fingerprint dropdown for `Changes` view is not rendering the dropdown correctly

image

This is how it should appear

image

### PR DESCRIPTION
**Pull request by johnaohara**
Fixes #867
- Add openapi doc to website

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Comment by johnaohara** [comment]
@jesperpedersen this failed the CI because of the linter, I need to fix that

**Comment by jesperpedersen** [comment]
@johnaohara Passed locally

**Comment by johnaohara** [comment]
The code is ok, but the local test does not run the linter

**Pull request closed without merging**
