### PR TITLE
Use specific `cmd` to install dependencies by quinoa

### PR DESCRIPTION
**Pull request by shivam-sharma7**

### CODE REVIEW

**Comment by jesperpedersen** [comment]
What is this for ?

**Comment by shivam-sharma7** [comment]
> What is this for ?

By default quinoa use `npm ci` which is install packages from .lock files and sometime this is give peer dep issue to avoid this we can use our own cmd like `npm install` what we use and this is download packages from `package.json file` and keep up to date with `.lock` file

**Comment by shivam-sharma7** [comment]
don't mind but happy to see you on Sunday,

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Pull request merged**
