### PR TITLE
Remove Maven wrapper scripts

### PR DESCRIPTION
**Pull request by jesperpedersen**

### CODE REVIEW

**Comment by johnaohara** [comment]
If we are removing the helper scripts from the Quarkus project, we need to document that devs need the maven installed with the correct version as a prerequisite to building the project; otherwise, the Quarkus maven plugins will not function.

**Comment by jesperpedersen** [comment]
Its in "Prerequisites"

**Comment by jesperpedersen** [comment]
We need to have a clear directory directory layout such that it is easy to figure out where your contribution goes

**Comment by rvansa** [comment]
What does clear directory layout have to do with Maven wrapper? Having that is a standard thing for any Quarkus project.

**Comment by rvansa** [comment]
To digress a bit, why are Keycloak, Grafana and PostgreSQL in *Prerequisites*?  You don't need to have that installed locally. On the other hand, you need either Docker or Podman.
Sure, we depend on these but they're transparently managed via images. So I wouldn't list them (we don't list Quarkus either and we depend on that...)

**Comment by jesperpedersen** [comment]
They are prerequisites since the test suite won't run without them - docker or podman is a way to get them running locally.

**Comment by rvansa** [comment]
In my view *Prerequisites* are the thing you need to do/get manually. Testsuite will run just fine even if you never touch them. I see these as *Dependencies*.

**Pull request merged**
