### PR TITLE
fixes #701 #702 #703 #729 refactored out postgres callbacks and message bus usage

### LINKED ISSUE #701: Refactor out logic from PostgreSQL
**To ease and increase adoption Horreum need to remove it's dependency on psql triggers and functions**

The goal is for Horreum to support different datasources for runs. All data/metadata generated by Horreum will continue to use postgres. This will also move all the logic into Horreum which will make it easier to maintain and test.

## SubTasks

- [ ] #702
- [ ] #703
- [x] #729
- [ ]  Refactor data out of Run into a separate datasource/table

### dataset_schemas
Generated by psql here: https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/resources/db/changeLog.xml#L2523

The table is used by both psql and Horreum several places.
When a new dataset is created it causes this trigger:
Generated by psql here: https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/resources/db/changeLog.xml#L3961

As it's out of scope to change the label/dataset processing of Horreum, we need to add logic in Horreum to create entries to this table identical to psql.

### LINKED ISSUE #702: Refactor out data deletes
# Delete Test:
 - test.delete() then TEST_DELETED is published on the messagebus which causes:
-  -  RunService trashes on all Runs with run.testId == testId
-  - AlertingService deletes all Variables with test.id == testId
-  - ExperimentService deletes all ExperimentProfiles with test.id == testId
-  - LogService deletes all DatasetLogs and TransformationLogs with test.id == testId
-  - ActionService deletes all Actions with test.id == testId
- - ReportService updates tablereportconfig.testid to NULL where testid == testId
-  - SubscriptionService delets all Watchers with test.id == testId

## psql:

- mdr_on_test_delete() is triggered before a test is deleted
- - this executes: `DELETE FROM missingdata_rule WHERE test_id = OLD.id;`
- - this will again trigger mdr_on_rule_delete() which executes:
- - - `DELETE FROM missingdata_ruleresult WHERE rule_id = OLD.id;`

# Delete Run:

- No real deletion of runs afaik:
- run trash seems to be triggered when a test is removed or with RunService.trash.
- the logic in horreum only set run.trashed = true and 
- removes all datasets with that run.id
- this will submit DATASET_DELETED for each dataset and RUN_TRASHED with run.testid

## psql: 

- rs_after_run_trash() is triggered when run.trash = true
- - which executes: `DELETE FROM run_schemas WHERE runid = OLD.id;`
- rs_after_run_update() is triggered when run.trash = false
- - which executes: https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/resources/db/changeLog.xml#L4010 NOTE: this should not be handled by this task, but the update task.
- before_run_delete() trigger is calling before_run_delete_func() for each row before delete
- - which executes: `DELETE FROM run_schemas WHERE runid = OLD.id;`
- after_run_delete() trigger is calling after_run_delete_func() for each row after delete:
- - `DELETE FROM dataset WHERE runid = OLD.id;`

# Delete Dataset:

## psql:

- mdr_before_delete() is triggered before delete on datased, it executes mdr_on_dataset_delete()
- - which executes: `DELETE FROM missingdata_ruleresult WHERE dataset_id = OLD.id;`
- lv_before_delete() is triggered before delete on dataset, it executes lv_before_dataset_delete_func()
- - which executes: `DELETE FROM label_values WHERE dataset_id = OLD.id; DELETE FROM dataset_schemas WHERE dataset_id = OLD.id;`
- 

# Delete Schema:
Before Schema.delete() is triggered, we do:

- `DELETE FROM label_extractors WHERE label_id IN (SELECT id FROM label WHERE schema_id = ?1)`
- `LabelDAO.delete("schema.id", id);`  - Note: look at Label below for more info on Label delete logic
- `DELETE FROM transformer_extractors WHERE transformer_id IN (SELECT id FROM transformer WHERE schema_id = ?1)`
- `DELETE FROM test_transformers WHERE transformer_id IN (SELECT id FROM transformer WHERE schema_id = ?1)`
- `TransformerDAO.delete("schema.id", id);`

## psql:

- before_schema_delete() is triggered before delete on Schema
- - this executes before_schema_delete_func() which runs:
- - `DELETE FROM run_schemas WHERE schemaid = OLD.id; DELETE FROM dataset_schemas WHERE schema_id = OLD.id;`
- lv_before_delete() is triggered before delete on label, it executeslv_before_label_delete_func()
- - which executes: `DELETE FROM label_values WHERE label_id = OLD.id;`

# Delete Label:
Labels contains a list of LabelExtractors that embedded to Label. When something happens to a Label it usually triggers logic on the Extractors.
In addition [LabelValues](https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/LabelDAO.java#L74) will be deleted if a Dataset is removed or Label is removed.
 
## psql:

- lv_before_delete() is triggered before delete on Label
- - this executes lv_before_label_delete_func() which runs:
- - `DELETE FROM label_values WHERE label_id = OLD.id;`
- lv_before_delete() is triggered before delete on LabelExtractors
- - this executes lv_before_le_delete_func() which runs:
- - `DELETE FROM label_values WHERE label_id = OLD.label_id;`
- - lv_after_delete() is triggered after delete on LabelExtractors:
- - this executes lv_after_le_delete_func() which runs:
- - https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/resources/db/changeLog.xml#L2563
- - this will insert schemaId and labelId on the label_recalc_queue
- - any insert on this table will trigger:
- - https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/resources/db/changeLog.xml#L3962
- - this will again trigger DatasetServiceImpl.onLabelChange
- - Delete of LabelValue (label_value) will trigger: [fp_after_lv_delete_func](https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/resources/db/changeLog.xml#L2942)
- - - This triggers delete in fingerprint and insert in fingerprint_recalc_queue

### PR DESCRIPTION
**Pull request by stalep**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by johnaohara** [comment]
Trying to add a new label to an existing schema is failing with the following exception:

```
2023-10-14 09:15:41,325 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-3) HTTP Request to /api/schema/1/labels failed, error id: caaf3619-6fa2-4c81-a6d0-91b4b51f1bb4-2: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
	at io.hyperfoil.tools.horreum.svc.SchemaServiceImpl_Subclass.addOrUpdateLabel(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.SchemaServiceImpl_ClientProxy.addOrUpdateLabel(Unknown Source)
	at io.hyperfoil.tools.horreum.api.services.SchemaService$quarkusrestinvoker$addOrUpdateLabel_36c89d04d369d1694a4cf9f6e63cafce6988aa22.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: jakarta.transaction.RollbackException: ARJUNA016102: The transaction is not active! Uid is 0:ffffc0a8446a:9e03:652a4c3f:450
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1261)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.hyperfoil.tools.horreum.server.BaseTransactionRetryInterceptor.intercept(BaseTransactionRetryInterceptor.java:29)
	at io.hyperfoil.tools.horreum.server.BaseTransactionRetryInterceptor_RequiredTransactionRetryInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	... 13 more
```

**Comment by stalep** [comment]
I've added an amqp queue for label update/add/delete.
I've not added a broker to podman/docker yet so atm the branch only works in dev mode.

**Comment by johnaohara** [comment]
@stalep I agree with the general direction of messaging, but I think we should use the constructs that the smallrye reactive messaging library provides i.e: http://smallrye.io/smallrye-reactive-messaging/4.7.0/concepts/blocking/

The current implementation using the smallrye context propagation managedExecutor is not handling failures and will take 1000 messages per channel an enqueue them in memory.  If horreum crashes, we will lose those messages because as far as the amq broker is concerned, they have been delivered.  We also have 3 native context switches per message received, if we use the smallrye reactive messaging @Blocking annotation, I think we will only have 2

**Comment by jesperpedersen** [comment]
Merged w/ some disabled test cases.

Thanks for your contribution !

**Pull request closed without merging**
