### PR TITLE
Fix keycloak deployment in dev profile

### LINKED ISSUE #1927: Missing Horreum default user in dev mode
**Describe the bug**

Horreum started up in development mode does not have the default `user` anymore.

Am I missing something?

**To Reproduce**

Start Horreum:
```bash
mvn -Dquarkus.test.continuous-testing=disabled quarkus:dev -pl 'horreum-backend'
```

Then open http://localhost:8080 and try to login using the default account.

I tried:
- `user/secret` which was the previous default
- `horreum.bootstrap/secret` just a try

Moreover in the logs I don't see the dummy password creation:
```bash
>>>
>>> Created temporary account horreum.bootstrap with password 4gGK8hcutXvbAF4p
>>>
```

**Notes**

I might be wrong but it looks like this has been introduced with https://github.com/Hyperfoil/Horreum/pull/1900, I tried to revert that and I was able to see again:
```bash
>>>
>>> Created temporary account horreum.bootstrap with password 4gGK8hcutXvbAF4p
>>>
```

**Version**

What is the version of Horreum ?

`master`

If you are using a development branch; what is the commit id ?

```
$ git rev-parse HEAD
2851657fa2b260123be0138a2818f109958c1199
```

### PR DESCRIPTION
**Pull request by barreiro**
fixes #1927

### CODE REVIEW

**Review by lampajr — COMMENTED** [review]
Thanks @barreiro, now it looks working when started in dev mode but I does not working anymore when using a prod (or any existing) database (but still started in dev mode.

It fails with:
```bash
Unable to list administrators: jakarta.ws.rs.ProcessingException: jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:652)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:424)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:134)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:102)
	at jdk.proxy6/jdk.proxy6.$Proxy232.getUserMembers(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.user.KeycloakUserBackend.administrators(KeycloakUserBackend.java:333)
	at io.hyperfoil.tools.horreum.svc.user.KeycloakUserBackend_ClientProxy.administrators(Unknown Source)
	at io.hyperfoil.tools.horreum.server.SecurityBootstrap.checkBootstrapAccount(SecurityBootstrap.java:119)
	at io.hyperfoil.tools.horreum.server.SecurityBootstrap.onStart(SecurityBootstrap.java:56)
```
So it looks like there is still some wrong configuration when using existing db

**Comment by lampajr** [comment]
> Thanks @barreiro, now it looks working when started in dev mode but I does not working anymore when using a prod (or any existing) database (but still started in dev mode.
> 
> It fails with:
> ```bash
> Unable to list administrators: jakarta.ws.rs.ProcessingException: jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
> 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:652)
> 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:424)
> 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:134)
> 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
> 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:102)
> 	at jdk.proxy6/jdk.proxy6.$Proxy232.getUserMembers(Unknown Source)
> 	at io.hyperfoil.tools.horreum.svc.user.KeycloakUserBackend.administrators(KeycloakUserBackend.java:333)
> 	at io.hyperfoil.tools.horreum.svc.user.KeycloakUserBackend_ClientProxy.administrators(Unknown Source)
> 	at io.hyperfoil.tools.horreum.server.SecurityBootstrap.checkBootstrapAccount(SecurityBootstrap.java:119)
> 	at io.hyperfoil.tools.horreum.server.SecurityBootstrap.onStart(SecurityBootstrap.java:56)
> ```
> So it looks like there is still some wrong configuration when using existing db

As we discussed this seems to be fixed by overriding the `secret` env property when using an existing database against the dev mode.

This change is a manual one, therefore the pr looks good to me!

**Review by lampajr — APPROVED** [review]

**Comment by barreiro** [comment]
thanks !!

**Review by lampajr — APPROVED** [review]
Tested locally and it works as expected!

**Pull request merged**
