### PR TITLE
Implement Horreum Dev services

### PR DESCRIPTION
**Pull request by johnaohara**
- All infrastructure now handled by quarkus:dev & testcontainers
- automatically apply postgres configuration
- improve example data loading
- speedup integration test build
- remove legacy scripts
- Update docs, remove unused infra dockerfiles, cleanup config
- Works natively on windows, (i.e. no need for WSL env now)

There are a couple of outstanding features to implement: 
- loading database from prod backup
- dev UI/URL for loading example data, removing final legacy '/infra-legacy' script

The following features have been verified to work in the following environments;

| Environment  | dev services |  Integration tests | example data |
| ------------- | ------------- | ------------- | ------------- |
| Linux (f38)  docker| ✓  | ✓ | ✓ |
| Linux (f38)  podman| ✓  | ✓ | ✓ |
| MacOS 13 (m2) podman | ✓ | ✓ | ✓ |
| Win 10 docker | ✓  | X | X |

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Failing locally as well

**Comment by johnaohara** [comment]
@jesperpedersen was working for me as maven had cached the parent pom, have now fixed that and the windows ci build, running again

**Comment by johnaohara** [comment]
I will squash all commits once the build passes in CI

**Comment by shivam-sharma7** [comment]
> I will squash all commits once the build passes in CI

@johnaohara don't you think so we should upgrade java 11 to 17 for this project if this is , would you like to share process?

**Comment by shivam-sharma7** [comment]
close: #588

**Comment by jesperpedersen** [comment]
Getting
```
Caused by: java.lang.RuntimeException: Quinoa package manager live coding port 3000 is still not listening after the checkTimeout.
	at io.quarkiverse.quinoa.deployment.packagemanager.PackageManager.dev(PackageManager.java:128)
	at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:133)
```

**Comment by johnaohara** [comment]
@jesperpedersen what platform is that on? is this with a clean install, with the node modules cleaned?

quinoa should be started in parallel with the other dev services

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !

**Comment by shivam-sharma7** [comment]
@johnaohara how get setup with docker for local dev?

**Pull request merged**
