### PR TITLE
Revert "Bump react-to-print from 2.14.15 to 2.15.1 in /horreum-web"

### PR DESCRIPTION
**Pull request by whitingjr**
This reverts commit 079ef80b41feaab49b79933c04f59230e135ee03.

### CODE REVIEW

**Comment by willr3** [comment]
Why does this need to revert?

**Comment by whitingjr** [comment]
@willr3 this commit included changes to package-lock.json that are excessively verbose. The whole file was reformatted.

**Comment by willr3** [comment]
> @willr3 this commit included changes to package-lock.json that are excessively verbose. The whole file was reformatted.

Ahh, I see it's reverting a recent commit. It is a shame that dependabot PRs are not formatting correctly

**Comment by whitingjr** [comment]
@willr3 I agree it is a shame. I'll be investigating what's not working as expected in the recently added workflow that is supposed to re-format to the correct format.

**Pull request merged**
