### PR TITLE
CI: check for uncommitted changes

### PR DESCRIPTION
**Pull request by lampajr**
Proposing to add a check for uncommitted changes during PR checks, this is going to ensure that all those autogenerated files are properly committed (doing this especially for the openapi spec)

## Changes proposed

- [x] Checks for uncommitted changes during pull request checks

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by lampajr** [comment]
This [job](https://github.com/Hyperfoil/Horreum/actions/runs/8781138745/job/24092507020?pr=1620) is exactly failing because there are some uncommitted changes:
```bash
Uncommitted file changes detected:  M docs/site/content/en/openapi/openapi.yaml
diff --git a/docs/site/content/en/openapi/openapi.yaml b/docs/site/content/en/openapi/openapi.yaml
index d3b5e1d..ddaf2e9 100644
--- a/docs/site/content/en/openapi/openapi.yaml
+++ b/docs/site/content/en/openapi/openapi.yaml
@@ -675,6 +675,7 @@ paths:
         description: query string to filter runs
         schema:
           type: string
+        example: $.*
       - name: matchAll
         in: query
         description: match all Runs?
```

This means that we missed to commit some auto-generated openapi changes

**Comment by lampajr** [comment]
If we agree on this change, I will commit the openapi changes as well

**Review by johnaohara — APPROVED** [review]
LGTM

**Comment by lampajr** [comment]
> The backport to `0.12.x` failed. Check the latest run for more details.

Created manual backport https://github.com/Hyperfoil/Horreum/pull/1632

**Pull request merged**
