### PR TITLE
Remove use of deprecated table

### LINKED ISSUE #1369: Remove UI dependencies on `@patternfly/react-table/deprecated`
**Describe the bug**

Some of the UI components are deprecated in patternfly 5, we should upgrade the components to the latest version, e.g. `@patternfly/react-table/deprecated`

### PR DESCRIPTION
**Pull request by barreiro**
fixes #1369 

I replaced the `Table` with a `DescriptionList` where appropriate

### CODE REVIEW

**Comment by willr3** [comment]
The only one I'm concerned with is the `About.tsx` change to `DescriptionList`. Have you looked at the before and after at different resolutions and looks ok?

**Comment by barreiro** [comment]
IMO `DescriptionList` is a more appropriate component to use in some situations (and does look very good). In `About.tsx` here is the before and after:

image

image

**Review by willr3 — APPROVED** [review]
lgtm

**Review by lampajr — APPROVED** [review]
Looks great to me, especially because it fixes the labelValues/dataset comparison overflow when changing the screen size 😄 

@barreiro could you please rebase and fix the conflict as I merged the "Dark theme switch" first? Then it's ready to go imo

**Comment by barreiro** [comment]
> Looks great to me, especially because it fixes the labelValues/dataset comparison overflow when changing the screen size 😄

yeah, I noticed that issue while testing and the fix was to simply wrap the table in a `InnerScrollContainer` component. 

> @barreiro could you please rebase and fix the conflict as I merged the "Dark theme switch" first? Then it's ready to go imo

done

**Pull request merged**
